### PR TITLE
Loosen upper bounds to build with newer versions

### PR DESCRIPTION
**Pull request by markus1189**
I bumped some bounds on dependencies, to make it build with newer versions.

### CODE REVIEW

**Comment by markus1189** [comment]
Would be cool to have this merged, because `iCalendar` does not build with e.g. 8.10.3

**Comment by NorfairKing** [comment]
+1 It looks like this package is not actively maintained, maybe we can have the haskell foundation have a look at this? @hecate

**Comment by Kleidukos** [comment]
Please follow this procedure if you need actions taken on this package: https://wiki.haskell.org/Taking_over_a_package

**Comment by NorfairKing** [comment]
@chrra what do you think?

**Comment by schoettl** [comment]
Hi there, chrra gave me merge rights. I close this PR in favor of #51 (merged).

**Comment by Kleidukos** [comment]
Welcome to our new maintainer :)

**Pull request closed without merging**
